name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test on ${{ matrix.os }} with ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        arch: [core2, nehalem, westmere, sandybridge, ivybridge, haswell, broadwell, skylake, knl, knm, skylake-avx512, cannonlake]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Build LuaJIT
        run: |
          if [[ "$(uname -s)" = Darwin ]]
          then
            export MACOSX_DEPLOYMENT_TARGET="$(sw_vers -productVersion)"
          fi
          make -j CCOPT_x64=-march=${{ matrix.arch }}

      - name: Run bytecode test
        run: |
          cd src
          touch empty.lua
          if ! ./luajit -b -o osx -a arm64 empty.lua empty.o
          then
            echo "::warning ::Unable to execute LuaJIT"
            exit 0
          fi

          file_output="$(file empty.o)"
          echo "$file_output" >> $GITHUB_STEP_SUMMARY
          if [[ "$file_output" = *"Mach-O"* ]]
            echo "::notice title=${{ matrix.os }}-${{ matrix.arch }} succeeded::${file_output}"
          then
            echo "::error title=${{ matrix.os }}-${{ matrix.arch }} failed::${file_output}"
            exit 1
          fi
